#
# Copyright (c) 2021-2026 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be released. Should be in format 1.y.z'
        required: true
        default: '2.y.z'

permissions:
  id-token: write  # Required for publishing to npmjs
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
      -
        name: "Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: "Release: publish to npmjs"
        run: ./make-release.sh ${{ github.event.inputs.version }}